with eada_renanmed as (
  select re.year,
    re.unitid as institution_id,
    re.opeid,
    institution_name,
    addr1_txt as address_1,
    addr2_txt as address_2,
    city_txt as city,
    state_cd as state,
    LEFT(zip_text, 5) as zip_code,
    -- classificationcode,
    classification_name as classification,
    -- classificationother,
    efmalecount as num_male_undergraduates,
    effemalecount as num_female_undergraduates,
    eftotalcount as num_undergraduates,
    sector_cd as sanction_id,
    sector_name as sanction_name,
    studentaid_men as athletic_student_aid_for_men,
    studentaid_women as athletic_student_aid_for_women,
    studentaid_coed as athletic_student_aid_for_coed,
    -- studentaid_total as athletic_student_aid,
    -- stuaid_men_ratio / 100.0 as athletic_student_aid_ratio_men,
    -- stuaid_women_ratio / 100.0 as athletic_student_aid_ratio_women,
    -- stuaid_coed_ratio / 100.0 as athletic_student_aid_coed_ratio,
    recruitexp_men as recruiting_expenses_for_men,
    recruitexp_women as recruiting_expenses_for_women,
    recruitexp_coed as recruiting_expenses_for_coed,
    -- recruitexp_total as recruiting_expenses_total,
    hdcoach_salary_men as head_coach_salaries_for_men,
    hdcoach_salary_women as head_coach_salaries_for_women,
    hdcoach_salary_coed as head_coach_salaries_for_coed,
    num_hdcoach_men as num_head_coaches_for_men,
    num_hdcoach_women as num_head_coaches_for_women,
    num_hdcoach_coed as num_head_coaches_for_coed,
    hdcoach_sal_fte_men as head_coach_salaries_fte_for_men,
    hdcoach_sal_fte_womn as head_coach_salaries_fte_for_women,
    hdcoach_sal_fte_coed as head_coach_salaries_fte_for_coed,
    fte_hdcoach_men as num_head_coach_fte_for_men,
    fte_hdcoach_women as num_head_coach_fte_for_women,
    fte_hdcoach_coed as num_head_coach_fte_for_coed,
    ascoach_salary_men as assistant_coach_salaries_for_men,
    ascoach_salary_women as assistant_coach_salaries_for_women,
    ascoach_salary_coed as assistant_coach_salaries_for_coed,
    num_ascoach_men as num_assistant_coaches_for_men,
    num_ascoach_women as num_assistant_coaches_for_women,
    num_ascoach_coed as num_assistant_coaches_for_coed,
    ascoach_sal_fte_men as assistant_coach_fte_salaries_for_men,
    ascoach_sal_fte_womn as assistant_coach_fte_salaries_for_women,
    ascoach_sal_fte_coed as assistant_coach_fte_salaries_for_coed,
    fte_ascoach_men as num_assistant_coach_fte_for_men,
    fte_ascoach_women as num_assistant_coach_fte_for_women,
    fte_ascoach_coed as num_assistant_coach_fte_for_coed,
    -- il_partic_men as num_participating_men_on_mens_teams,
    -- il_partic_women as num_participating_women_on_womens_teams,
    il_partic_coed_men as num_male_participating_in_coed_teams,
    il_partic_coed_women as num_female_participating_in_coed_teams,
    il_sum_partic_men as num_male_participation_dup,
    il_sum_partic_women as num_female_participation_dup,
    il_opexpperpart_men as expenses_per_participant_on_mens_teams,
    il_opexpperteam_men as total_expenses_for_mens_teams,
    il_opexpperpart_women as expenses_per_participant_on_womens_teams,
    il_opexpperteam_women as total_expenses_for_womens_teams,
    il_total_opexp_menwomen as total_expenses_for_men_and_women,
    il_opexpperpart_coed_men as expenses_per_participant_men_on_coed_teams,
    il_opexpperteam_coed_men as total_expenses_for_men_on_coed_teams,
    il_opexp_part_coed_women as expenses_per_participant_women_on_coed_teams,
    il_opexp_team_coed_women as total_expenses_for_women_on_coed_teams,
    il_total_opexp_coedteam as total_expenses_per_coed_team,
    il_sum_opexpperpart_men as expenses_per_particpant_men_including_coed,
    il_sum_opexpperteam_men as total_expenses_men_including_coed,
    il_sum_opexpperpart_women as expenses_per_participant_women_including_coed,
    il_sum_opexpperteam_women as total_expenses_women_including_coed,
    il_total_opexp_inclcoed as total_expenses_including_coed,
    -- il_men_ftheadcoach_male,
    -- il_men_ptheadcoach_male,
    -- il_men_ftunivemploy_male,
    -- il_men_ptunivemploy_male,
    -- il_men_ftheadcoach_fem,
    -- il_men_ptheadcoach_fem,
    -- il_men_ftunivemploy_fem,
    -- il_men_ptunivemploy_fem,
    -- il_men_total_headcoach,
    -- il_women_fthdcoach_male,
    -- il_women_pthdcoach_male,
    -- il_women_ftunivemp_male,
    -- il_women_ptunivemp_male,
    -- il_women_fthdcoach_fem,
    -- il_women_pthdcoach_fem,
    -- il_women_ftunivemp_fem,
    -- il_women_ptunivemp_fem,
    -- il_women_total_hdcoach,
    -- il_coed_fthdcoach_male,
    -- il_coed_pthdcoach_male,
    -- il_coed_ftunivemp_male,
    -- il_coed_ptunivemp_male,
    -- il_coed_fthdcoach_fem,
    -- il_coed_pthdcoach_fem,
    -- il_coed_ftunivemp_fem,
    -- il_coed_ptunivemp_fem,
    -- il_coed_total_hdcoach,
    -- il_sum_fthdcoach_male,
    -- il_sum_pthdcoach_male,
    -- il_sum_ftunivemp_male,
    -- il_sum_ptunivemp_male,
    -- il_sum_fthdcoach_fem,
    -- il_sum_pthdcoach_fem,
    -- il_sum_ftunivemp_fem,
    -- il_sum_ptunivemp_fem,
    -- il_sum_total_hdcoach,
    -- il_men_ftascoach_male,
    -- il_men_ptascoach_male,
    -- il_men_ftacunivemp_male,
    -- il_men_ptacunivemp_male,
    -- il_men_ftasstcoach_fem,
    -- il_men_ptasstcoach_fem,
    -- il_men_ftacunivemp_fem,
    -- il_men_ptacunivemp_fem,
    -- il_men_total_asstcoach,
    -- il_women_ftascoach_male,
    -- il_women_ptascoach_male,
    -- il_women_ftacunemp_male,
    -- il_women_ptacunemp_male,
    -- il_women_ftastcoach_fem,
    -- il_women_ptastcoach_fem,
    -- il_womn_ftacunivemp_fem,
    -- il_womn_ptacunivemp_fem,
    -- il_women_total_astcoach,
    -- il_coed_ftascoach_male,
    -- il_coed_ptascoach_male,
    -- il_coed_ftacunemp_male,
    -- il_coed_ptacunemp_male,
    -- il_coed_ftastcoach_fem,
    -- il_coed_ptastcoach_fem,
    -- il_coed_ftacunivemp_fem,
    -- il_coed_ptacunivemp_fem,
    -- il_coed_total_astcoach,
    -- il_sum_ftascoach_male,
    -- il_sum_ptascoach_male,
    -- il_sum_ftacunivemp_male,
    -- il_sum_ptacunivemp_male,
    -- il_sum_ftascoach_fem,
    -- il_sum_ptascoach_fem,
    -- il_sum_ftacunivemp_fem,
    -- il_sum_ptacunivemp_fem,
    -- il_sum_total_asstcoach,
    il_rev_men as total_revenue_mens_teams,
    il_rev_women as total_revenue_womens_teams,
    il_total_rev_menwomen as total_revenue_mens_and_womens_teams,
    il_rev_coed_men as total_revenue_men_on_coed_teams,
    il_rev_coed_women as total_revenue_women_on_coed_teams,
    il_total_rev_coed as total_revenue_coed,
    il_revenue_menall as total_revenue_men_including_coed,
    il_revenue_womenall as total_revenue_women_including_coed,
    IL_TOTAL_REVENUE_ALL as total_revenue_all_teams,
    -- IL_EXP_MEN,
    -- IL_EXP_WOMEN,
    -- IL_TOTAL_EXP_MENWOMEN,
    -- IL_EXP_COED_MEN,
    -- IL_EXP_COED_WOMEN,
    -- IL_TOTAL_EXP_COED,
    -- IL_EXPENSE_MENALL,
    -- IL_EXPENSE_WOMENALL,
    -- IL_TOTAL_EXPENSE_ALL,
    UNDUP_CT_PARTIC_MEN as unduplicated_men_participating_in_mens_and_coed,
    UNDUP_CT_PARTIC_WOMEN as unduplicated_women_participating_in_womens_and_coed,
    TOT_REVENUE_ALL_NOTALLOC as total_revenue_not_allocated_by_gender_or_sport,
    TOT_EXPENSE_ALL_NOTALLOC as total_expenses_not_allocated_by_gender_or_sport,
    GRND_TOTAL_REVENUE as grand_total_revenue,
    GRND_TOTAL_EXPENSE as grand_total_expenses,
    rpp.num_male_practice_players
  from raw_eada re
  left join raw_practice_players rpp
    on re.unitid = rpp.unitid
    and re.year = rpp.year
)

select *,
  num_male_undergraduates::float / NULLIF(num_undergraduates,0) as percentage_of_male_undergraduates,
  num_female_undergraduates::float / NULLIF(num_undergraduates,0) as percentage_of_female_undergraduates
from eada_renanmed
