SELECT year, institution_id, opeid, institution_name, address_1, address_2, city, state, zip_code, classification,
'Male' as sex, sanction_id, sanction_name,
  num_male_undergraduates as num_undergraduates,
  athletic_student_aid_for_men as athletic_student_aid,
  recruiting_expenses_for_men as recruiting_expenses,
  head_coach_salaries_for_men as avg_head_coach_salaries,
  num_head_coaches_for_men as num_head_coaches,
  head_coach_salaries_fte_for_men as avg_head_coach_salaries_fte,
  num_head_coaches_fte_for_men as num_head_coaches_fte,
  assistant_coach_salaries_for_men as avg_assistant_coach_salaries,
  num_assistant_coaches_for_men as num_assistant_coaches,
  assistant_coach_fte_salaries_for_men as avg_assistant_coach_fte_salaries,
  num_assistant_coaches_fte_for_men as num_assistant_coaches_fte,
  num_male_participation_dup as num_participation,
  expenses_per_participant_on_mens_teams as expenses_per_participant,
  total_expenses_for_mens_teams as total_expenses,
  expenses_per_particpant_men_including_coed as expenses_per_particpant_including_coed,
  total_expenses_men_including_coed as total_expenses_including_coed,
  total_revenue_mens_teams as total_revenue,
  total_revenue_men_including_coed as total_revenue_including_coed,
  unduplicated_men_participating_in_mens_and_coed as unduplicated_participating_including_coed,
  num_male_practice_players
FROM {{ ref('eada') }}

UNION ALL

SELECT year, institution_id, opeid, institution_name, address_1, address_2, city, state, zip_code, classification,
'Female' as sex, sanction_id, sanction_name,
  num_female_undergraduates as num_undergraduates,
  athletic_student_aid_for_women as athletic_student_aid,
  recruiting_expenses_for_women as recruiting_expenses,
  head_coach_salaries_for_women as avg_head_coach_salaries,
  num_head_coaches_for_women as num_head_coaches,
  head_coach_salaries_fte_for_women as avg_head_coach_salaries_fte,
  num_head_coaches_fte_for_women as num_head_coaches_fte,
  assistant_coach_salaries_for_women as avg_assistant_coach_salaries,
  num_assistant_coaches_for_women as num_assistant_coaches,
  assistant_coach_fte_salaries_for_women as avg_assistant_coach_fte_salaries,
  num_assistant_coaches_fte_for_women as num_assistant_coaches_fte,
  num_female_participation_dup as num_participation_dup,
  expenses_per_participant_on_womens_teams as expenses_per_participant,
  total_expenses_for_womens_teams as total_expenses,
  expenses_per_participant_women_including_coed as expenses_per_particpant_including_coed,
  total_expenses_women_including_coed as total_expenses_including_coed,
  total_revenue_womens_teams as total_revenue,
  total_revenue_women_including_coed as total_revenue_including_coed,
  unduplicated_women_participating_in_womens_and_coed as unduplicated_participating_including_coed,
  num_male_practice_players
  FROM {{ ref('eada') }}
